services:
db:
image: postgres:16
environment:
POSTGRES_USER: notes
POSTGRES_PASSWORD: notes
POSTGRES_DB: notes
ports:
- "5432:5432"
volumes:
- dbdata:/var/lib/postgresql/data


backend:
build: ./backend
environment:
PORT: 8080
DB_DSN: postgres://notes:notes@db:5432/notes?sslmode=disable
JWT_SECRET: devsecretchange
CORS_ORIGIN: http://localhost:5100
ports:
- "1010:1010"
depends_on:
- db


frontend:
build: ./frontend
environment:
VITE_API_URL: http://localhost:1010
ports:
- "5100:5100"
depends_on:
- backend


volumes:
dbdata: {}