version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      PORT: 8080
      DB_DSN: postgres://notes:notes@db:5432/notes?sslmode=disable
      JWT_SECRET: devsecretchange
      CORS_ORIGIN: http://localhost:5100
    ports:
      - "1010:8080"   # Host 1010 -> Container 8080
    depends_on:
      - db
    networks:
      - cloudnotes-net

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://backend:8088   # use container name internally
    ports:
      - "5100:80"    # Host 5100 -> Nginx port 80
    depends_on:
      - backend
    networks:
      - cloudnotes-net

volumes:
  dbdata: {}

networks:
  cloudnotes-net:
    driver: bridge
